export const state = {
  screen: 'home', 
  onboardingStep: 0,
  onboardingData: { name: '', gender: 'female', goals: [], dailyMinutes: 15, daysPerWeek: 6, startDate: '' },
  workoutSteps: [],
  currentStepIndex: 0,
  showingSectionIntro: false,
  currentSectionId: null,
  todayFocus: null,
  timerInterval: null,
  timerRunning: false,
  timerRemaining: 0,
  timerTotal: 0,
  repsRemaining: 0,
  repsTotal: 0,
  comboPhase: 'reps',
  exerciseComplete: false,
  skippedCount: 0,
  skippedCoreCount: 0,
  liveBpm: null,
  liveKcal: null,
  bluetoothDeviceId: null,
  trackerInterval: null,
  justFinishedWorkout: false,
  // Social/Auth State
  currentUser: null,
  authLoading: true,
  leaderboard: [],
  loadingLeaderboard: false,
  myCommunities: [],
  activeCommunity: 'global',
};
